extends: default

rules:
  document-start: disable
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
  comments:
    require-starting-space: true
    min-spaces-from-content: 1
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0
